---
- name: 'Instalação de Requisistos e Update'
  apt:
    update_cache: yes 
    cache_valid_time: 3600
    name: "{{ item }}"
    state: latest
  loop: "{{ packages_pre_docker }}"
  become: yes

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    state: present
  become: yes

- name: 'Instalação Docker'
  apt:
    update_cache: yes 
    cache_valid_time: 3600
    name: "{{ item }}"
    state: latest
  loop: "{{ packages_docker }}"
  become: yes

- name: 'Download Docker-Compose'
  command: curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  become: yes

- name: 'Altera a permissão de execução do Docker-Compose'
  file: 
    dest: /usr/local/bin/docker-compose 
    mode: a+x
  become: yes

- name: 'Cria Link Simbolico'
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
  become: yes
#  notify: restart docker
